### ISSUE TITLE
New PTB Patch 5.5.0, some files do not classify and classify them in _StreamedFiles

### ISSUE THREAD

**Issue by Neinndall** [Fabien2S/DBDToolbox#8] opened 2022-01-05 19:55 UTC
Some audio files (+240 files) are including it in the _StreamedFiles folder where I suppose they are the ones that the program doesn't know what they are!
![_StreamedFiles Folder](https://user-images.githubusercontent.com/66384195/148280301-122cf65b-548c-4b17-b65a-1557c238484d.PNG)

I have checked through a file called "SoundbanksInfo" and they are there, I don't know if you will apply a hotfix for it!

I want to give you more info!
![4566](https://user-images.githubusercontent.com/66384195/148280340-fc4400e8-063b-49a2-8b3b-d3f55bb22eec.PNG)

The file "65519131" is a new audio file from "ambience" but it seems that your program did not classify it because it does not detect it or cannot find it! and it is in the _StreamedFiles folder, where I suppose the program should find it in its respective folder

**Comment by Fabien2S** [comment] 2022-01-12 16:24
I just notice the notification, unfortunately I don't have the time to install the PTB.

The __StreamedFiles_ folder is for sounds that are marked as "streamed" **by the developers**, which is mainly used for large sound files, such as musics.

For the unknown files, as far as I remember, they are left in place when not found in the _SoundbanksInfo.xml_ file, so either my software has a bug, or the sound names were not present in the said _SoundbanksInfo.xml_ file. (Again, if I remember)

Did you get any errors in the console during the extraction ?

I will try to investigate when the 5.5.0 is released on the main branch, but feel free to ping me about it, I will probably forget

**Comment by Fabien2S** [comment] 2022-01-12 16:36
By any chances, can you send me the SoundbanksInfo.xml ? Thanks you

**Comment by Neinndall** [comment] 2022-01-17 11:06
Sry I've been sick.. however, I'll send you the file :3
https://drive.google.com/file/d/1cac-KeHuPgVt4a1ea-A6bqkdoJCTxECz/view?usp=sharing

Edit: If I remember correctly, I got some ERROR or WARNING, but I think those ERROR (the problems I had were the ones I reported to you a few weeks ago)

**Comment by Fabien2S** [comment] 2022-01-17 12:46
No worries, hoping you are doing better!

The file you sent it a .json file.
Are there no more .xml files included (SoundbanksInfo.xml) ? Perhaps they changed to file format

I think we better off waiting for the official release and see if it works.

If they changed the file format it could took me a day of work to update it,
If the unnamed file ids are not present, then I wouldn't be able to do anything.

I could also force the software to convert unnamed files to .ogg, thats would be better

**Comment by Th3Nigh7mare** [comment] 2022-01-18 11:25
Hello! I tell you, they added .json formats, but they also follow the .xml files
Right now I don't have the SoundbanksInfo.xml from the PTB, but the patch will be out soon (25th)

**Comment by Neinndall** [comment] 2022-01-18 11:28
Hello and thx! I tell you, they added .json formats, but they also follow the .xml files
Edit: I found it. I hope you can hotfix with this, thank you very much :3
https://drive.google.com/file/d/19yBg408ptpYFLzRmjNnMm-R08GY73LhM/view?usp=sharing

**Comment by Fabien2S** [comment] 2022-01-19 21:21
Thanks you!

From what I saw, the file IDs are not present in the xml file, so the software cannot rename them

This happens quite often during PTB, so it _should_ be fixed in the final release

Only time will tell!

**Comment by Neinndall** [comment] 2022-01-19 21:30
Hello Fabien!

I rectify, there are some that are, not many. I left you an example above "65519131.wem"

**Comment by Fabien2S** [comment] 2022-01-20 12:37
I saw your example, but when I search the string "65519131" in the file you sent (SoundbanksInfo.xml), I can't find anything.
Am I missing something ? I'm pretty tired so I can just be completely blind

Update: I got it, "65519131" is in _SoundbanksInfo.xml_ of the current version, but missing from the PTB one. We need to wait for the final release, maybe they will includes an up-to-date _SoundbanksInfo.xml_ file

**Comment by Neinndall** [comment] 2022-01-26 23:25
Hello Fabian!

Just 2 days ago the final version 5.5.0 came out, and I was using the latest version again, and many errors(fails) appeared!
I could share a txt document with all the information of the console! However, if you need anything, let me know! By the way, the files are still .xml, but they added versions of those .json files too!
[log_console_5.5.0.txt](https://github.com/Fabien2S/DBDToolbox/files/7946289/log_console_5.5.0.txt)

**Comment by Fabien2S** [comment] 2022-01-29 10:29
I push an update which should get rid of most of the errors.
However, after some investigations :

- The "Survivor_Female[...]" and "Survivor_Male[...]" that fail to extract are not relevant : the sound effects are now located in "SRV_[...]" so everything is correctly exported
- I cannot convert files in the __StreamedFiles_ when they're not renamed (Too much refactoring in the code, and I don't really have time for it)
- If you find any other errors, please tell me, but I'm pretty sure for the most part, everything is "working as intended"

For the json files, they are pretty much the same as the XML, I don't really know if they will drop the xml one at some point, of if both will exists. In the meantime, I modified the software to extract them too, but I don't do anthing with them for the moment

**Comment by Neinndall** [comment] 2022-01-29 15:48
I downloaded it and I will use it, thank you very much for your work! Any errors I see, I'll report it!

Edit: I leave the thread open?

**Comment by Fabien2S** [comment] 2022-01-30 11:50
I'll close it for now, you can reopen it if needed

**Closed as completed by Fabien2S** 2022-01-30 11:50 UTC
Labels: bug

**Comment by Th3Nigh7mare** [comment] 2022-03-08 11:23
Hello Fabian, I open this thread to see if it is possible to have contact by discord (Th3Nigh7mare#9843), to comment on a topic about DBD that has nothing to do with this tool, to see if you could help me! I'll close the thread later :)

**Comment by Th3Nigh7mare** [comment] 2022-04-05 18:16
Hi Fabien! I have this, new patch 5.7.0 PTB
![234](https://user-images.githubusercontent.com/66384195/161822794-90b2d1a1-aed2-4d2b-af95-3b2e64f1e5a7.PNG)

I hope u can fix it!
